### ISSUE TITLE
Phunk does not launch

### ISSUE THREAD

**Issue by alucardxs** [shibadevs/phunk#5]
Hello,
F
irst, : Thanks for this great tool.
Second : I can't get it to work (the latest version). I installed both .NET and Java but the .exe does not launch, W11 is telling me that this program is nopt compatible with a PC.
Third : is it normal the TEMp auto clean within 30 seconds ? i can't do anything at that speed.
Any idea ?

Thanks

**Comment by shibadevs** [comment]
Hello, I newly tried it on my PC and its also doing the same thing for me. Please use the older versions for now (1.0.1.5). And to those who are experiencing this too, I am very sorry for the inconvenience. As for the temp auto clean, that feature has not yet been implemented, so I don't know what you are talking about regarding the speed. Just a side note, if you start Phunker, the files from the temp will be overwritten. Deleting the files when starting will be implemented in the next update.
