### ISSUE TITLE
Trojan detected in latest version. Phunk 1.0.2.5 (Java Hotfix)

### ISSUE THREAD

**Issue by PabloKQ** [shibadevs/phunk#6]
![Captura de pantalla 2024-04-08 203214](https://github.com/shibadevs/phunk/assets/3965383/2fbcb5b9-e6e2-44fc-b776-307b7cb48101)

**Comment by shibadevs** [comment]
Im not entirely sure why its showing trojan, I tried using it on my PC and the only error I have is why it is not opening. However I'll get into the bottom of this and try to locate issue. Thank you.
