### ISSUE TITLE
Java Error & version is not upto date

### ISSUE THREAD

**Issue by JarJarBlinkz** [shibadevs/phunk#7]
i have everything installed and got the latest version and still getting missing requirements: java 8+ also version is not upto date: 21.0

![image](https://github.com/shibadevs/phunk/assets/104454560/8d0fd25c-dda3-4e35-bf1f-301c5561c4a2)

**Comment by shibadevs** [comment]
Hello, it seems like you have the Java SE Development Kit 21.0 which is not compatible with Phunk. Please uninstall it via the Control Panel and download the supported version here: https://www.java.com/en/download/ (Java 8)
